src/post/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import PostAndCommentsView, EditPostView, CreatePostView, EditPostDialogView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PostAndCommentsView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(EditPostView.as_view()), name='edit'),
    url(r'^(?P<pk>\d+)/edit_dialog/$', login_required(EditPostDialogView.as_view()), name='edit_dialog'),
    url(r'^new/$', login_required(CreatePostView.as_view()), name='new_post'),
    url(r'^(?P<pk>\d+)/rating/', include('rating.urls', namespace="rating")),
    url(r'^(?P<pk>\d+)/comment/', include('comment.urls', namespace="comment")),

]

src/post/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.timezone import now


class PostQuerySet(models.QuerySet):

    def shown_for(self, user):
        return self.filter(Q(author=user) | Q(is_deleted=False))

    def published(self):
        return self.filter(Q(pub_date__lt=now()))

    def search(self, text):
        return self.filter(Q(title__icontains=text))

    def stat(self):
        return self.select_related('author')\
            .prefetch_related('comments__author')\
            .annotate(comments_count=models.Count('comments'))\
            .annotate(rating_value=models.Sum('votes__value'))


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_posts')
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
    # image = models.ImageField(upload_to='images/')
    # encoded_image = models.CharField(max_length=1000000)
    encoded_image = models.TextField()
    is_deleted = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now)

    objects = PostQuerySet.as_manager()

    def get_rating(self):
        votes = self.votes
        return sum(votes.value for votes in votes.all())

    def __str__(self):
        return self.title

    def __unicode__(self):
        return str(self.pk) + ' ' + str(self.title)

src/post/forms.py
from django import forms

from .models import Post


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'encoded_image')
        widgets = {'encoded_image': forms.HiddenInput()}


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'encoded_image')
        widgets = {'encoded_image': forms.HiddenInput()}


class SearchForm(forms.Form):
    text = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Search',
        'style': 'color: #FFFFFF;',
    }))
    order = forms.ChoiceField(choices=(
        ('-created_date', 'Date desc'),
        ('created_date', 'Date asc'),
        ('author', 'Author'),
    ))
    # direction = forms.ChoiceField(choices=(('ascending', 'Ascending'), ('descending', 'Descending')))

src/post/views.py
import logging

from django.db import models
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.timezone import now
from django.views.generic import CreateView, ListView,  UpdateView

from comment.models import Comment
from .forms import SearchForm, NewPostForm, EditPostForm
from .models import Post

logger = logging.getLogger(__name__)


class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    queryset = Post.objects.all()
    ordering = 'created_date'
    paginate_by = 4
    search_form = None

    def dispatch(self, request, *args, **kwargs):
        self.search_form = SearchForm(request.GET)
        return super(PostListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        search_form = SearchForm(self.request.GET)
        if search_form.is_valid():
            print(search_form.cleaned_data)
            order = search_form.cleaned_data['order']
            search = search_form.cleaned_data['text']
        else:
            order = self.request.GET.get('order_by', '-created_date')       # wtf?
            search = ''
        # queryset = Post.objects.filter(Q(title__icontains=search) and
        #                                Q(pub_date__lt=now()) and
        #                                Q(is_deleted=False))
        if self.request.user.is_authenticated():
            queryset = Post.objects.all().published().search(search).shown_for(self.request.user).order_by(order)
        else:
            queryset = Post.objects.all().published().search(search).order_by(order)
        queryset = queryset.stat()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form
        return context


class CreatePostView(CreateView):
    model = Post
    template_name = 'post/post_create.html'
    form_class = NewPostForm

    def get_success_url(self):
        return reverse('post:detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.author = self.request.user
        logger.info('i am logging')
        return super(CreatePostView, self).form_valid(form)


class PostAndCommentsView(CreateView):
    model = Comment
    template_name = "post/post.html"
    fields = ('text', )
    post = None

    def dispatch(self, request, pk=None, *args, **kwargs):
        # qs = Post.objects.stat()
        # self.post = get_object_or_404(qs, pk=pk)
        self.post = Post.objects.all().prefetch_related('comments', 'comments__author').select_related('author').get(pk=pk)
        return super(PostAndCommentsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PostAndCommentsView, self).get_context_data(**kwargs)
        context['post'] = self.post
        return context


class EditPostView(UpdateView):
    model = Post
    template_name = 'post/post_edit.html'
    form_class = EditPostForm

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

    def get_success_url(self):
        return reverse('post:detail', kwargs={'pk': self.object.id})


class EditPostDialogView(UpdateView):
    model = Post
    template_name = 'post/post_edit_dialog.html'
    form_class = EditPostForm

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

    def get_success_url(self):
        return reverse('post:detail', kwargs={'pk': self.object.id})
    
    def form_valid(self, form):
        response = super(EditPostDialogView, self).form_valid(form)
        return HttpResponse('OK')
        # return HttpResponse({'status': 'OK'})

    # def form_invalid(self, form):
    #     return HttpResponse({'status': 'FAIL', 'errors': form.errors.as_json()})

src/post/templates/post/post.html
{% extends "base.html" %}

{% load i18n %}
{% load cache %}

{% block title %}
    <div class="post-title">{{ post.title }}</div>
{% endblock %}

{% block content %}

    <div class="card" style="display: inline-block; margin-top: 50px;">

        <!--Card image-->
        <a href="{% url 'post:detail' pk=post.pk %}">
            <img class="img-fluid" src="{{ post.encoded_image }}" alt="Card image cap" width="720">
        </a>
        <!--/.Card image-->

        <!--Card content-->
        <div class="card-block" style="max-width: 800px;">
            <!--Title-->
            <h4 class="card-title"><a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }}</a></h4>
            <!--Text-->
            <p class="card-text">
                {% blocktrans with date=post.created_date|date:"Y - m - d H:i" %}Created  {{ date }}
                    by{% endblocktrans %}
                <a href="{% url 'user:user_view' pk=post.author.id %}">
                    {{ post.author }}
                </a>
                <br>
                {% trans 'Rating ' %}<span class="rating-value"
                                           data-post-id="{{ post.id }}">{{ post.rating_value }}</span>
            </p>

            {% if user.is_authenticated %}
                <div style="display:inline-block;">
                    {#                        {% csrf_token %}#}
                    <button type="submit" class="vote-up"
                            data-url-vote-up="{% url 'post:rating:vote_up' pk=post.pk %}">
                        {% trans 'Vote UP' %}
                    </button>
                    <button type="submit" class="vote-down"
                            {#                    <button type="submit" class="btn btn-secondary btn-sm vote-down"#}
                            data-url-vote-down="{% url 'post:rating:vote_down' pk=post.pk %}">
                        {% trans 'Vote DOWN' %}
                    </button>
                </div>
                {% if user == post.author %}
                    {#                    <form action="{% url 'post:edit' pk=post.pk %}">#}
                    {#                        <button type="submit" class="btn btn-primary btn-sm" id="post-edit-link">Edit</button>#}
                    {#                    </form>#}
                    <a href="{% url 'post:edit_dialog' pk=post.pk %}"
                       id="post-edit-link">
                        {% trans 'Edit' %}
                    </a>

                {% endif %}
            {% endif %}
        </div>
        <!--/.Card content-->

    </div>
    <br>

    <div class="post-comments">{% include 'comment/comments.html' %}</div>
    {% if user.is_authenticated %}
        <form action="{% url 'post:comment:new_comment' pk=post.pk %}" method="POST" style="margin-top: 50px;">
            {% csrf_token %}
            <div class="md-form" style="max-width: 1000px;">{{ form.text }}</div>
            <button type="submit" class="btn btn-secondary btn-sm" width="40">{% trans 'Add comment' %}</button>
        </form>
    {% endif %}

    <div class="bgdialog">
        <div class="dialog">
            Edit post
        </div>
    </div>

{% endblock %}

src/post/templates/post/post_create.html
{% extends "base.html" %}

{% block content %}
    <h1>New post</h1>
    {% if form.errors %}
        <div id="form-error">
            <p>The operation could not be performed because one or more error(s) occurred.<br/>Please resubmit the form
                after making the following changes:</p>
            <ul>
                {% for field in form %}
                    <li>{{ field.errors|striptags }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div>{{ form.title }}</div>
{#        <div>{{ form.image }}</div>#}
        <input id="id_encoded_image" maxlength="10000" name="encoded_image" type="hidden">
        <div>
            <canvas id="simple_sketch" width="800" height="300" class="sketch"></canvas>

        </div>
        {#        <div>{{ form.image }}</div>#}
{#        <input id="btn" type="button" value="button"/>#}

        <button id='submit' type="submit" class="btn btn-default">Save</button>

    </form>


    <script type="text/javascript">
        $(function draw() {
            $('#simple_sketch').sketch();
        });
        $(function () {
            $('#submit').click(function () {
                $(document.getElementById('id_encoded_image').value = document.getElementById('simple_sketch').toDataURL())
            })
        })
    </script>
{% endblock %}

src/post/templates/post/post_edit.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit post</h1>
   {% if form.errors %}
        <div id="form-error">
            <p>The operation could not be performed because one or more error(s) occurred.<br/>Please resubmit the form
                after making the following changes:</p>
            <ul>
                {% for field in form %}
                    <li>{{ field.errors|striptags }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div>{{ form.title }}</div>
{#        <div>{{ form.image }}</div>#}
        <input id="id_encoded_image" maxlength="10000" name="encoded_image" type="hidden">
        <div>
            <canvas id="simple_sketch" width="800" height="300" class="sketch"></canvas>

        </div>
        {#        <div>{{ form.image }}</div>#}
{#        <input id="btn" type="button" value="button"/>#}

        <button id='submit' type="submit" class="btn btn-default">Save</button>

    </form>


    <script type="text/javascript">
        $(function draw() {
            $('#simple_sketch').sketch();
        });
        $(function () {
            $('#submit').click(function () {
                $(document.getElementById('id_encoded_image').value = document.getElementById('simple_sketch').toDataURL())
            })
        })
    </script>
{% endblock %}

src/post/templates/post/post_edit_dialog.html
{#{% if form.errors %}#}
{#    <div id="form-error">#}
{#        <p>The operation could not be performed because one or more error(s) occurred.<br/>Please resubmit the form#}
{#            after making the following changes:</p>#}
{#        <ul>#}
{#            {% for field in form %}#}
{#                <li>{{ field }}{{ field.errors|striptags }}</li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </div>#}
{#{% endif %}#}
<form method="POST" enctype="multipart/form-data" class="ajax-form" action="{% url 'post:edit_dialog' pk=post.pk %}">
    {% csrf_token %}
    <div>{{ form.title }}</div>
    {% for error in form.title.errors %}
        <b>{{ error }}</b>
    {% endfor %}
    <input id="id_encoded_image" maxlength="10000" name="encoded_image" type="hidden">
    <div>
        <canvas id="simple_sketch" width="800" height="300" class="sketch"></canvas>
    </div>
    <button id='submit' type="submit" class="btn btn-default">Save</button>

</form>


<script type="text/javascript">
    $(function draw() {
        $('#simple_sketch').sketch();
    });
    $(document).on('click', '#submit', function () {
        $(document.getElementById('id_encoded_image').value = document.getElementById('simple_sketch').toDataURL())
{#        // jquery#}
    });
</script>

src/post/templates/post/post_list.html
{% extends "base.html" %}
{% load cache %}

{% block content %}

    {% for post in object_list %}
        <!--Card-->
        <div class="card" style="display: inline-block; margin-top: 50px;">

            <!--Card image-->
            <a href="{% url 'post:detail' pk=post.pk %}">
                <img class="img-fluid" src="{{ post.encoded_image }}" alt="Card image cap" width="720">
            </a>
            <!--/.Card image-->

            <!--Card content-->
            <div class="card-block" style="max-width: 800px;">
                <!--Title-->
                <h4 class="card-title"><a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }}</a></h4>
                <!--Text-->
                <p class="card-text">
                    Created {{ post.created_date|date:"Y - m - d H:i" }} by
                    <a href="{% url 'user:user_view' pk=post.author.id %}">
                        {{ post.author }}
                    </a>
                    {% cache 60 "comments" post.pk %}<div>{{ post.comments_count }} comments</div>{% endcache %}
                    <div>{{ post.rating_value }} rating</div>
                </p>
                {#                <a href="#" class="btn btn-primary">Button</a>#}
            </div>
            <!--/.Card content-->

        </div>
        <br>
        <!--/.Card-->

    {% endfor %}
    {% if paginator.num_pages > 1 %}

        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="/page{{ page_obj.previous_page_number }}?{{ request.GET.urlencode }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link"
                           href="/page{{ page_obj.previous_page_number }}?{{ request.GET.urlencode }}">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="/page{{ page_obj.number }}?{{ request.GET.urlencode }}">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="/page{{ page_obj.next_page_number }}?{{ request.GET.urlencode }}">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="/page{{ page_obj.next_page_number }}?{{ request.GET.urlencode }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>

    {% endif %}

{% endblock %}